import { useEffect, useMemo, useState } from "react";
import ReactFlow, { Background, Controls, MarkerType, Position } from "reactflow";
import type { Edge, Node } from "reactflow";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type SwapPairsExample } from "./data";
import { createSwapPairsDryRun } from "./dryRun";

export default function SwapPairsVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [values, setValues] = useState(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createSwapPairsDryRun(values), [values]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selected = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((current) => current + 1), 650); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  const nodes = useMemo<Node[]>(() => [{ id: "dummy", position: { x: -150, y: 130 }, sourcePosition: Position.Right, targetPosition: Position.Left, className: ["combo-node", frame.activeId === "dummy" ? "is-active" : ""].filter(Boolean).join(" "), data: { label: <div className="combo-node-content"><strong>dummy</strong><span>{frame.prevId === "dummy" ? "prev" : "sentinel"}</span></div> } }, ...values.map((value, index) => { const id = `node-${index}`; return { id, position: { x: index * 155, y: 130 }, sourcePosition: Position.Right, targetPosition: Position.Left, className: ["combo-node", frame.activeId === id ? "is-active" : frame.targetId === id ? "is-pointer-change" : frame.completedIds.includes(id) ? "is-complete" : ""].filter(Boolean).join(" "), data: { label: <div className="combo-node-content"><strong>{value}</strong><span>{frame.prevId === id ? "prev" : frame.firstId === id ? "first" : frame.secondId === id ? "second" : frame.afterId === id ? "after" : frame.completedIds.includes(id) ? "swapped" : `node ${index}`}</span></div> } }; })], [frame.activeId, frame.afterId, frame.completedIds, frame.firstId, frame.prevId, frame.secondId, frame.targetId, values]);
  const edges = useMemo<Edge[]>(() => Object.entries(frame.links).flatMap(([source, target]) => target ? [{ id: `${source}-${target}`, source, target, type: "smoothstep", label: "next", labelBgBorderRadius: 6, labelBgPadding: [6, 3], markerEnd: { type: MarkerType.ArrowClosed }, animated: frame.activeId === source, style: { stroke: frame.activeId === source ? "#d9973c" : "#52728e", strokeWidth: frame.completedIds.includes(source) ? 2.5 : 1.6 } }] : []), [frame.activeId, frame.completedIds, frame.links]);
  function load(example: SwapPairsExample) { setExampleId(example.id); setValues(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const parsed: unknown = JSON.parse(text); if (!Array.isArray(parsed) || parsed.length > 10 || !parsed.every((value) => typeof value === "number" && Number.isFinite(value))) throw new Error(); setExampleId(0); setValues(parsed as number[]); setStep(0); setPlaying(false); setError(""); } catch { setError("Use a JSON list of up to 10 numbers, for example [1,2,3,4]."); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>head JSON<textarea aria-label="list input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load list</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current result"}</span><code>{JSON.stringify(frame.result ?? "pending")}</code></div></aside><section className="flow-panel combo-flow-panel"><div className="panel-heading"><h2>In-place next pointers</h2><span>yellow: rewritten pointer</span></div><ReactFlow nodes={nodes} edges={edges} defaultViewport={{ x: 140, y: 50, zoom: 0.7 }} minZoom={0.18} maxZoom={1.6} nodeOrigin={[0.5, 0]}><Background gap={22} size={1} /><Controls /></ReactFlow></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>pointer variables</h3><div className="token-list"><span>prev = {label(frame.prevId, values)}</span><span>first = {label(frame.firstId, values)}</span><span>second = {label(frame.secondId, values)}</span><span>after = {label(frame.afterId, values)}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
function label(id: string | null, values: number[]): string { return id === null ? "None" : id === "dummy" ? "dummy" : String(values[Number(id.slice(5))]); }
