import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type MergeSortedArrayInput } from "./data";
import { createMergeSortedArrayDryRun } from "./dryRun";

export default function MergeSortedArrayVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<MergeSortedArrayInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createMergeSortedArrayDryRun(input.nums1, input.m, input.nums2, input.n), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selectedExample = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((value) => value + 1), 560); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  function load(example: (typeof examples)[number]) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const candidate = JSON.parse(text) as MergeSortedArrayInput; if (!candidate || !Array.isArray(candidate.nums1) || !Array.isArray(candidate.nums2) || !candidate.nums1.every(Number.isFinite) || !candidate.nums2.every(Number.isFinite) || !Number.isInteger(candidate.m) || !Number.isInteger(candidate.n) || candidate.m < 0 || candidate.n < 0 || candidate.m > candidate.nums1.length || candidate.n !== candidate.nums2.length || candidate.nums1.length !== candidate.m + candidate.n) throw new Error(); setInput(candidate); setExampleId(0); setStep(0); setPlaying(false); setError(""); } catch { setError('Use JSON such as {"nums1":[1,2,3,0,0,0],"m":3,"nums2":[2,5,6],"n":3}.'); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load arrays</button></div><div className="expected-output"><span>{selectedExample ? selectedExample.label + " output" : "Current result"}</span><code>{JSON.stringify(frame.result ?? selectedExample?.output ?? "pending")}</code></div></aside><section className="flow-panel merge-array-flow-panel"><div className="panel-heading"><h2>Backfill the Destination Tail</h2><span>write = {frame.write}</span></div><div className="merge-array-stage"><ArrayRow label="nums1 destination" values={frame.nums1} pointer={frame.p1} write={frame.write} live={frame.m} chosen={frame.chosen} source="nums1" /><ArrayRow label="nums2 source" values={frame.nums2} pointer={frame.p2} write={null} live={frame.n} chosen={frame.chosen} source="nums2" /><div className="merge-pointer-grid"><span>p1 = {frame.p1}</span><span>p2 = {frame.p2}</span><span>write = {frame.write}</span></div><div className="product-phase"><span>current action</span><strong>{frame.title}</strong><p>{frame.detail}</p></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={"event-card " + frame.kind}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>three pointers</h3><div className="token-list"><span>p1 = {frame.p1}</span><span>p2 = {frame.p2}</span><span>write = {frame.write}</span><span>chosen = {frame.chosen ?? "-"}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
function ArrayRow({ label, values, pointer, write, live, chosen, source }: { label: string; values: number[]; pointer: number; write: number | null; live: number; chosen: "nums1" | "nums2" | null; source: "nums1" | "nums2" }) { return <section className="merge-array-row"><h3>{label}</h3><div>{values.map((value, index) => <span className={[index === pointer ? "is-pointer" : "", index === write ? "is-write" : "", index >= live && source === "nums1" ? "is-spare" : "", chosen === source && index === (source === "nums1" ? pointer + 1 : pointer + 1) ? "is-chosen" : ""].filter(Boolean).join(" ")} key={index}><b>{value}</b><em>{index === pointer ? source === "nums1" ? "p1" : "p2" : index === write ? "write" : index}</em></span>)}</div></section>; }
