export type MinimumHeightTreesInput = { n: number; edges: number[][] };

export const title = "310. Minimum Height Trees";
export const examples = [
  { id: 1, label: "LeetCode 1", input: { n: 4, edges: [[1, 0], [1, 2], [1, 3]] }, output: [1] },
  { id: 2, label: "LeetCode 2", input: { n: 6, edges: [[3, 0], [3, 1], [3, 2], [3, 4], [5, 4]] }, output: [3, 4] },
] satisfies Array<{ id: number; label: string; input: MinimumHeightTreesInput; output: number[] }>;
export const defaultExample = examples[0]!;
export const codeLines = [
  "from typing import List",
  "from collections import deque",
  "",
  "class Solution:",
  "    def findMinHeightTrees(self, n: int, edges: List[List[int]]) -> List[int]:",
  "",
  "        if n == 1:",
  "            return [0]",
  "",
  "        graph = [[] for _ in range(n)]",
  "",
  "        degree = [0] * n",
  "",
  "        for a, b in edges:",
  "            graph[a].append(b)",
  "            graph[b].append(a)",
  "",
  "            degree[a] += 1",
  "            degree[b] += 1",
  "",
  "        queue = deque()",
  "",
  "        # degree == 1 的节点就是叶子节点",
  "        for i in range(n):",
  "            if degree[i] == 1:",
  "                queue.append(i)",
  "",
  "        remaining = n",
  "",
  "        # 一层一层删除叶子",
  "        # 最后只剩 1 或 2 个节点，就是树的中心",
  "        while remaining > 2:",
  "",
  "            size = len(queue)",
  "",
  "            # 删除这一层的所有叶子",
  "            remaining -= size",
  "",
  "            for _ in range(size):",
  "                leaf = queue.popleft()",
  "",
  "                for nei in graph[leaf]:",
  "                    degree[nei] -= 1",
  "",
  "                    if degree[nei] == 1:",
  "                        queue.append(nei)",
  "",
  "        return list(queue)",
];
