import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const appDirectory = resolve(scriptDirectory, "..");
const outputPath = resolve(appDirectory, "src/catalog/companyCollections/snapshots.generated.ts");
const defaultInputPath = resolve(scriptDirectory, "data/official-company-collections.json");

const companies = [
  { name: "Google", favoriteSlug: "google-three-months" },
  { name: "Amazon", favoriteSlug: "amazon-three-months" },
  { name: "TikTok", favoriteSlug: "tiktok-three-months" },
];

const difficultyByApiValue = {
  EASY: "Easy",
  MEDIUM: "Medium",
  HARD: "Hard",
};

function inputPathFromArgs(args) {
  const inputFlag = args.indexOf("--input");

  if (inputFlag === -1) {
    return defaultInputPath;
  }

  const path = args[inputFlag + 1];
  if (!path) {
    throw new Error("--input requires a JSON file path");
  }

  return resolve(path);
}

function sourceUrlFor(company) {
  return `https://leetcode.com/company/${company.name.toLowerCase()}/?favoriteSlug=${company.favoriteSlug}`;
}

function normalizeQuestions(company, questions) {
  const ids = new Set();

  const problems = questions.map((question) => {
    const id = Number(question.questionFrontendId);
    const difficulty = difficultyByApiValue[question.difficulty];
    const frequency = Number(question.frequency);

    if (!Number.isInteger(id) || id <= 0 || !question.title || !question.titleSlug || !difficulty) {
      throw new Error(`${company.name}: received an invalid question from LeetCode`);
    }

    if (!Number.isFinite(frequency) || frequency < 0) {
      throw new Error(`${company.name}: received an invalid frequency for ${question.title}`);
    }

    if (ids.has(id)) {
      throw new Error(`${company.name}: duplicate frontend question id ${id}`);
    }

    ids.add(id);
    return {
      id,
      title: question.title,
      difficulty,
      frequency,
      sourceUrl: `https://leetcode.com/problems/${question.titleSlug}`,
    };
  });

  return problems.sort((left, right) => right.frequency - left.frequency || left.id - right.id);
}

function parseOfficialExport(rawExport) {
  if (rawExport?.format !== "algotrace-official-company-collections/v1") {
    throw new Error("Expected an AlgoTrace official company collection export");
  }

  if (!rawExport.fetchedAt || Number.isNaN(Date.parse(rawExport.fetchedAt))) {
    throw new Error("Official company export is missing a valid fetchedAt timestamp");
  }

  const exportsByName = new Map(rawExport.collections?.map((collection) => [collection.name, collection]));

  return companies.map((company) => {
    const collection = exportsByName.get(company.name);

    if (!collection || collection.favoriteSlug !== company.favoriteSlug || collection.sourceUrl !== sourceUrlFor(company)) {
      throw new Error(`${company.name}: official three-month export was missing or did not match its source`);
    }

    if (!Array.isArray(collection.questions) || collection.questions.length !== collection.totalLength) {
      throw new Error(`${company.name}: export must contain every question in the official list`);
    }

    return {
      name: company.name,
      label: `${company.name} · 3 months`,
      snapshotAt: new Date(rawExport.fetchedAt).toISOString(),
      sourceUrl: sourceUrlFor(company),
      problems: normalizeQuestions(company, collection.questions),
    };
  });
}

function formatSource(collections) {
  return `// Generated by scripts/refreshCompanyCollections.mjs. Do not edit by hand.\n` +
    `import type { CompanyCollection } from "./types";\n\n` +
    `export const companyCollectionSnapshots: readonly CompanyCollection[] = ${JSON.stringify(collections, null, 2)} as const;\n`;
}

async function main() {
  const inputPath = inputPathFromArgs(process.argv.slice(2));
  const rawExport = JSON.parse(await readFile(inputPath, "utf8"));
  const collections = parseOfficialExport(rawExport);
  const nextSource = formatSource(collections);

  await mkdir(dirname(outputPath), { recursive: true });

  const previousSource = await readFile(outputPath, "utf8").catch(() => "");
  if (previousSource !== nextSource) {
    await writeFile(outputPath, nextSource, "utf8");
    console.log(`Updated ${outputPath} from ${inputPath}`);
  } else {
    console.log("Company collection snapshots are already current.");
  }
}

await main();
