import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const appDirectory = resolve(scriptDirectory, "..");
const outputPath = resolve(appDirectory, "src/catalog/companyCollections/snapshots.generated.ts");
const sourceRepository = "https://github.com/dr-o-ne/leetcode-company-problem-frequency";

const companies = [
  { name: "Google", file: "google.md" },
  { name: "Amazon", file: "amazon.md" },
  { name: "TikTok", file: "tiktok.md" },
];

const difficultyNames = new Set(["Easy", "Medium", "Hard"]);

async function fetchText(url) {
  const response = await fetch(url, {
    headers: { "User-Agent": "AlgoTrace-company-snapshot-refresh" },
  });

  if (!response.ok) {
    throw new Error(`Request failed (${response.status}): ${url}`);
  }

  return response.text();
}

function parseRows(markdown, company, questionBySlug) {
  const rows = markdown
    .split("\n")
    .filter((line) => line.startsWith("|"))
    .slice(2)
    .map((line) => line.split("|").slice(1, -1).map((cell) => cell.trim()));
  const problems = [];
  const ids = new Set();

  for (const [rowCompany, title, difficulty, times, period, sourceUrl] of rows) {
    if (rowCompany !== company || period !== "0 - 3 months") {
      continue;
    }

    if (!difficultyNames.has(difficulty)) {
      throw new Error(`${company}: invalid difficulty for ${title}: ${difficulty}`);
    }

    const slug = new URL(sourceUrl).pathname.split("/").filter(Boolean).at(-1);
    const id = slug && questionBySlug.get(slug);
    const frequency = Number.parseInt(times, 10);

    if (!id || !Number.isInteger(frequency) || frequency < 0) {
      throw new Error(`${company}: could not validate ${title}`);
    }

    if (ids.has(id)) {
      throw new Error(`${company}: duplicate problem id ${id}`);
    }

    ids.add(id);
    problems.push({ id, title, difficulty, frequency, sourceUrl });
  }

  if (!problems.length) {
    throw new Error(`${company}: no 0 - 3 months problems found`);
  }

  return problems.sort((left, right) => right.frequency - left.frequency || left.id - right.id);
}

async function fetchQuestionIds() {
  const payload = JSON.parse(await fetchText("https://leetcode.com/api/problems/all/"));
  const questionBySlug = new Map();

  for (const entry of payload.stat_status_pairs ?? []) {
    const slug = entry.stat?.question__title_slug;
    const id = Number(entry.stat?.frontend_question_id);

    if (slug && Number.isInteger(id) && id > 0) {
      questionBySlug.set(slug, id);
    }
  }

  if (!questionBySlug.size) {
    throw new Error("LeetCode question index was empty");
  }

  return questionBySlug;
}

async function fetchSnapshotAt(file) {
  const commits = JSON.parse(
    await fetchText(
      `https://api.github.com/repos/dr-o-ne/leetcode-company-problem-frequency/commits?path=companies/${file}&per_page=1`,
    ),
  );
  const snapshotAt = commits[0]?.commit?.committer?.date;

  if (!snapshotAt || Number.isNaN(Date.parse(snapshotAt))) {
    throw new Error(`Could not determine source timestamp for ${file}`);
  }

  return new Date(snapshotAt).toISOString();
}

function formatSource(collections) {
  return `// Generated by scripts/refreshCompanyCollections.mjs. Do not edit by hand.\n` +
    `import type { CompanyCollection } from "./types";\n\n` +
    `export const companyCollectionSnapshots: readonly CompanyCollection[] = ${JSON.stringify(collections, null, 2)} as const;\n`;
}

async function main() {
  const questionBySlug = await fetchQuestionIds();
  const collections = await Promise.all(
    companies.map(async ({ name, file }) => {
      const rawUrl = `https://raw.githubusercontent.com/dr-o-ne/leetcode-company-problem-frequency/main/companies/${file}`;
      const [markdown, snapshotAt] = await Promise.all([fetchText(rawUrl), fetchSnapshotAt(file)]);

      return {
        name,
        label: `${name} · 3 months`,
        snapshotAt,
        sourceUrl: `${sourceRepository}/blob/main/companies/${file}`,
        problems: parseRows(markdown, name, questionBySlug),
      };
    }),
  );
  const nextSource = formatSource(collections);
  await mkdir(dirname(outputPath), { recursive: true });

  const previousSource = await readFile(outputPath, "utf8").catch(() => "");
  if (previousSource !== nextSource) {
    await writeFile(outputPath, nextSource, "utf8");
    console.log(`Updated ${outputPath}`);
  } else {
    console.log("Company collection snapshots are already current.");
  }
}

await main();
