import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type PartitionListInput } from "./data";
import { createPartitionListDryRun } from "./dryRun";

export default function PartitionListVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<PartitionListInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createPartitionListDryRun(input.head, input.x), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selectedExample = examples.find((example) => example.id === exampleId); const processed = new Set(frame.processed);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((value) => value + 1), 570); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  function load(example: (typeof examples)[number]) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const candidate = JSON.parse(text) as PartitionListInput; if (!candidate || !Array.isArray(candidate.head) || !candidate.head.every(Number.isFinite) || !Number.isFinite(candidate.x)) throw new Error(); setInput(candidate); setExampleId(0); setStep(0); setPlaying(false); setError(""); } catch { setError('Use JSON such as {"head":[1,4,3,2,5,2],"x":3}.'); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load list</button></div><div className="expected-output"><span>{selectedExample ? selectedExample.label + " output" : "Current result"}</span><code>{JSON.stringify(frame.result ?? selectedExample?.output ?? "pending")}</code></div></aside><section className="flow-panel partition-list-flow-panel"><div className="panel-heading"><h2>Stable Two-List Partition</h2><span>x = {input.x}</span></div><div className="partition-list-stage"><section className="partition-source"><h3>source</h3><div>{input.head.map((value, index) => <span className={[processed.has(index) ? "is-processed" : "", index === frame.currentIndex ? "is-current" : ""].filter(Boolean).join(" ")} key={index}><b>{value}</b><em>{index === frame.currentIndex ? "head" : "node " + index}</em></span>)}</div></section><ListLane label={"small (< " + input.x + ")"} values={frame.small} tone="small" /><ListLane label={"large (>= " + input.x + ")"} values={frame.large} tone="large" /><div className="partition-result"><span>joined result</span><strong>{frame.result ? "[" + frame.result.join(", ") + "]" : "small_tail -> large_dummy.next"}</strong></div><div className="product-phase"><span>current action</span><strong>{frame.title}</strong><p>{frame.detail}</p></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={"event-card " + frame.kind}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>list tails</h3><div className="token-list"><span>small = [{frame.small.join(", ")}]</span><span>large = [{frame.large.join(", ")}]</span><span>head = {frame.currentIndex === null ? "None" : input.head[frame.currentIndex]}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
function ListLane({ label, values, tone }: { label: string; values: number[]; tone: "small" | "large" }) { return <section className={"partition-lane " + tone}><h3>{label}</h3><div>{values.length ? values.map((value, index) => <span key={index}><b>{value}</b>{index < values.length - 1 ? <ArrowRight size={17} /> : null}</span>) : <em>{"dummy -> None"}</em>}</div></section>; }
