import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type HappyNumberInput } from "./data";
import { createHappyNumberDryRun } from "./dryRun";

export default function HappyNumberVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<HappyNumberInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createHappyNumberDryRun(input.n), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selected = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((current) => current + 1), 650); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  const load = (example: typeof defaultExample) => { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); };
  const loadInput = () => { try { const parsed: unknown = JSON.parse(text); if (!valid(parsed)) throw new Error(); setExampleId(0); setInput(parsed); setStep(0); setPlaying(false); setError(""); } catch { setError('Use {"n":19}; n must be a positive integer no larger than 10,000,000.'); } };
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="happy number input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load input</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current result"}</span><code>{frame.result === null ? "pending" : String(frame.result)}</code></div></aside><section className="flow-panel product-flow-panel"><div className="panel-heading"><h2>Digit-square sequence</h2><span>n = {frame.current}</span></div><div className="product-stage"><div className="product-numbers">{frame.digits.map((digit, index) => <div className={frame.phase === "transform" ? "product-number is-current" : "product-number"} key={`${index}-${digit}`}><span>digit {index}</span><strong>{digit}² = {digit * digit}</strong></div>)}</div><div className="product-phase"><span>next number</span><strong>{frame.next ?? "waiting"}</strong><p>{frame.detail}</p></div><div className="product-state-grid"><div className="product-state is-emphasized"><span>seen</span><strong>{frame.seen.length ? `{${frame.seen.join(", ")}}` : "{}"}</strong></div><div className="product-state is-result"><span>result</span><strong>{frame.result === null ? "searching" : String(frame.result)}</strong></div></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>current variables</h3><div className="token-list"><span>n = {frame.current}</span><span>next = {frame.next ?? "-"}</span><span>seen size = {frame.seen.length}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}

function valid(value: unknown): value is HappyNumberInput { return typeof value === "object" && value !== null && "n" in value && typeof value.n === "number" && Number.isInteger(value.n) && value.n > 0 && value.n <= 10_000_000; }
