import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type SortColorsInput } from "./data";
import { createSortColorsDryRun } from "./dryRun";

export default function SortColorsVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<SortColorsInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createSortColorsDryRun(input.nums), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selectedExample = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((value) => value + 1), 520); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  function load(example: (typeof examples)[number]) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const candidate = JSON.parse(text) as SortColorsInput; if (!candidate || !Array.isArray(candidate.nums) || !candidate.nums.every((value) => value === 0 || value === 1 || value === 2)) throw new Error(); setInput(candidate); setExampleId(0); setStep(0); setPlaying(false); setError(""); } catch { setError('Use JSON such as {"nums":[2,0,2,1,1,0]}.'); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load colors</button></div><div className="expected-output"><span>{selectedExample ? selectedExample.label + " output" : "Current result"}</span><code>{JSON.stringify(frame.result ?? selectedExample?.output ?? "pending")}</code></div></aside><section className="flow-panel sort-colors-flow-panel"><div className="panel-heading"><h2>Dutch National Flag</h2><span>unknown: {Math.max(0, frame.high - frame.mid + 1)}</span></div><div className="sort-colors-stage"><div className="color-array">{frame.nums.map((value, index) => <div className={["color-cell", "is-" + value, index === frame.compared ? "is-current" : "", frame.swapped?.includes(index) ? "is-swapped" : ""].filter(Boolean).join(" ")} key={index}><span>{index === frame.low ? "low" : index === frame.mid ? "mid" : index === frame.high ? "high" : ""}</span><strong>{value}</strong><em>i = {index}</em></div>)}</div><div className="color-regions"><span className="zero">0 region: [0, {frame.low - 1}]</span><span className="unknown">unknown: [{frame.mid}, {frame.high}]</span><span className="two">2 region: [{frame.high + 1}, {frame.nums.length - 1}]</span></div><div className="product-phase"><span>current action</span><strong>{frame.title}</strong><p>{frame.detail}</p></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={"event-card " + frame.kind}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>pointers</h3><div className="token-list"><span>low = {frame.low}</span><span>mid = {frame.mid}</span><span>high = {frame.high}</span><span>nums = [{frame.nums.join(", ")}]</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
