import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type RemoveElementInput } from "./data";
import { createRemoveElementDryRun } from "./dryRun";

export default function RemoveElementVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<RemoveElementInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createRemoveElementDryRun(input.nums, input.val), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selectedExample = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((value) => value + 1), 620); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  function load(example: (typeof examples)[number]) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const candidate = JSON.parse(text) as RemoveElementInput; if (!candidate || !Array.isArray(candidate.nums) || !candidate.nums.every(Number.isFinite) || !Number.isFinite(candidate.val)) throw new Error(); setInput(candidate); setExampleId(0); setStep(0); setPlaying(false); setError(""); } catch { setError('Use JSON such as {"nums":[3,2,2,3],"val":3}.'); } }
  const output = selectedExample?.output ?? frame.result;
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load input</button></div><div className="expected-output"><span>{selectedExample ? selectedExample.label + " output" : "Current result"}</span><code>k = {output.k ?? "?"}, nums = {JSON.stringify(output.nums)}</code></div></aside><section className="flow-panel dedupe-flow-panel"><div className="panel-heading"><h2>In-place Filter</h2><span>remove val = {input.val}</span></div><div className="dedupe-stage"><div className="dedupe-array">{frame.nums.map((value, index) => <div className={["dedupe-cell", index < frame.write ? "is-prefix" : "", frame.read === index ? "is-fast" : "", frame.write === index ? "is-slow" : "", frame.result.k !== null && index >= frame.result.k ? "is-ignored" : ""].filter(Boolean).join(" ")} key={index}><strong>{value}</strong><span>i={index}</span><div className="pointer-tags">{frame.read === index ? <em>read</em> : null}{frame.write === index ? <em>write</em> : null}</div></div>)}</div><div className="dedupe-result-row"><span>retained prefix</span><code>{JSON.stringify(frame.result.nums)}</code></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={"event-card " + frame.kind}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>pointers</h3><div className="token-list"><span>read = {frame.read ?? "-"}</span><span>write = {frame.write}</span><span>val = {frame.val}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
