import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type SearchInsertInput } from "./data";
import { createSearchInsertDryRun } from "./dryRun";

export default function SearchInsertVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<SearchInsertInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createSearchInsertDryRun(input.nums, input.target), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selectedExample = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((value) => value + 1), 620); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  function load(example: (typeof examples)[number]) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const candidate = JSON.parse(text) as SearchInsertInput; if (!candidate || !Array.isArray(candidate.nums) || !candidate.nums.every(Number.isFinite) || !candidate.nums.every((value, index) => index === 0 || candidate.nums[index - 1]! < value) || !Number.isFinite(candidate.target)) throw new Error(); setInput(candidate); setExampleId(0); setStep(0); setPlaying(false); setError(""); } catch { setError('Use sorted JSON such as {"nums":[1,3,5,6],"target":2}.'); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load input</button></div><div className="expected-output"><span>{selectedExample ? selectedExample.label + " output" : "Current result"}</span><code>{frame.result ?? selectedExample?.output ?? "pending"}</code></div></aside><section className="flow-panel binary-flow-panel"><div className="panel-heading"><h2>Lower-Bound Search</h2><span>target = {input.target}</span></div><div className="binary-stage"><div className="binary-array">{input.nums.map((value, index) => <div className={["binary-cell", index >= frame.left && index <= frame.right ? "in-window" : "is-discarded", index === frame.left ? "is-left" : "", index === frame.mid ? "is-mid" : "", index === frame.right ? "is-right" : "", frame.result === index ? "is-found" : ""].filter(Boolean).join(" ")} key={index}><strong>{value}</strong><span>{index === frame.left ? "left" : index === frame.mid ? "mid" : index === frame.right ? "right" : "i = " + index}</span></div>)}</div><div className="insert-slot"><span>insertion boundary</span><strong>{frame.result === null ? "searching" : "index " + frame.result}</strong></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={"event-card " + frame.kind}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>boundary</h3><div className="token-list"><span>left = {frame.left}</span><span>mid = {frame.mid ?? "-"}</span><span>right = {frame.right}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
