import { useEffect, useMemo, useState } from "react";
import ReactFlow, { Background, Controls, MarkerType, Position } from "reactflow";
import type { Edge, Node } from "reactflow";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import { flattenTree } from "../0094-binary-tree-inorder-traversal/dryRun";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type SameTreeExample } from "./data";
import { createSameTreeDryRun } from "./dryRun";

export default function SameTreeVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState({ p: defaultExample.p, q: defaultExample.q }); const [text, setText] = useState(JSON.stringify({ p: defaultExample.p, q: defaultExample.q })); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createSameTreeDryRun(input.p, input.q), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const pTree = useMemo(() => flattenTree(input.p), [input.p]); const qTree = useMemo(() => flattenTree(input.q), [input.q]); const selected = examples.find((item) => item.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((current) => current + 1), 650); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  const nodes = useMemo<Node[]>(() => [...makeNodes(pTree, "p", -270, frame.pId), ...makeNodes(qTree, "q", 270, frame.qId)], [frame.pId, frame.qId, pTree, qTree]);
  const edges = useMemo<Edge[]>(() => [...makeEdges(pTree, "p", frame.pId), ...makeEdges(qTree, "q", frame.qId)], [frame.pId, frame.qId, pTree, qTree]);
  function load(item: SameTreeExample) { const next = { p: item.p, q: item.q }; setExampleId(item.id); setInput(next); setText(JSON.stringify(next)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const parsed: unknown = JSON.parse(text); if (!parsed || typeof parsed !== "object" || !Array.isArray((parsed as { p?: unknown }).p) || !Array.isArray((parsed as { q?: unknown }).q)) throw new Error(); const next = parsed as { p: Array<number | null>; q: Array<number | null> }; if (![...next.p, ...next.q].every((value) => value === null || (typeof value === "number" && Number.isFinite(value)))) throw new Error(); setExampleId(0); setInput(next); setStep(0); setPlaying(false); setError(""); } catch { setError('Use {"p":[1,2,3],"q":[1,2,3]}.'); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((item) => <button className={item.id === exampleId ? "active" : ""} key={item.id} onClick={() => load(item)} type="button">{item.id}</button>)}</div></div><div className="input-grid"><label>p and q JSON<textarea aria-label="tree pair JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load trees</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current result"}</span><code>{String(frame.result ?? "pending")}</code></div></aside><section className="flow-panel combo-flow-panel"><div className="panel-heading"><h2>Paired tree comparison</h2><span>p on left, q on right</span></div><ReactFlow nodes={nodes} edges={edges} defaultViewport={{ x: 440, y: 52, zoom: 0.88 }} minZoom={0.18} maxZoom={1.6} nodeOrigin={[0.5, 0]}><Background gap={22} size={1} /><Controls /></ReactFlow></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>current pair</h3><div className="token-list"><span>p = {frame.pId ?? "None"}</span><span>q = {frame.qId ?? "None"}</span></div></div><div className="state-block"><h3>call stack</h3><div className="token-list">{frame.stack.length ? frame.stack.map((entry, index) => <span key={`${entry}-${index}`}>{entry}</span>) : <em>empty</em>}</div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
type Flat = ReturnType<typeof flattenTree>[number];
function makeNodes(tree: Flat[], prefix: string, xShift: number, activeId: string | null): Node[] { return tree.map((node) => ({ id: `${prefix}-${node.id}`, position: { x: xShift + xFor(node.layoutIndex), y: Math.floor(Math.log2(node.layoutIndex + 1)) * 132 }, sourcePosition: Position.Bottom, targetPosition: Position.Top, className: ["combo-node", "bst-node", activeId === node.id ? "is-active" : ""].filter(Boolean).join(" "), data: { label: <div className="combo-node-content"><strong>{node.value}</strong><span>{prefix}{activeId === node.id ? " current" : ""}</span></div> } })); }
function makeEdges(tree: Flat[], prefix: string, activeId: string | null): Edge[] { return tree.filter((node) => node.parentId).map((node) => ({ id: `${prefix}-${node.parentId}-${node.id}`, source: `${prefix}-${node.parentId}`, target: `${prefix}-${node.id}`, type: "straight", label: node.side, labelBgBorderRadius: 6, labelBgPadding: [6, 3], markerEnd: { type: MarkerType.ArrowClosed }, animated: node.id === activeId })); }
function xFor(index: number): number { const d = Math.floor(Math.log2(index + 1)); const first = 2 ** d - 1; return (index - first - (2 ** d - 1) / 2) * (160 / (2 ** Math.max(d - 1, 0))); }
