import type { FrameKind } from "../../shared/types";
type Node = { id: string; value: number; left: Node | null; right: Node | null };
export type KthSmallestBstFrame = { kind: FrameKind; phase: "start" | "descend" | "push" | "pop" | "count" | "right" | "found" | "done"; title: string; detail: string; activeLines: number[]; activeId: string | null; stack: string[]; visitedIds: string[]; visitedValues: number[]; kRemaining: number; result: number | null; };
export function createKthSmallestBstDryRun(values: Array<number | null>, k: number): { frames: KthSmallestBstFrame[] } {
  const root = build(values); const frames: KthSmallestBstFrame[] = []; const stack: Node[] = []; const visitedIds: string[] = []; const visitedValues: number[] = []; let node: Node | null = root; let remaining = k; let result: number | null = null;
  const push = (frame: Omit<KthSmallestBstFrame, "stack" | "visitedIds" | "visitedValues" | "kRemaining">) => frames.push({ ...frame, stack: stack.map((entry) => entry.id), visitedIds: [...visitedIds], visitedValues: [...visitedValues], kRemaining: remaining });
  push({ kind: "start", phase: "start", title: `Find the ${k}${suffix(k)} smallest value`, detail: "Inorder traversal of a BST visits values in increasing order.", activeLines: [3, 4], activeId: root?.id ?? null, result: null });
  while (stack.length || node) {
    push({ kind: "visit", phase: "descend", title: "Walk down the left spine", detail: "A smaller value may still be in the left subtree, so postpone the current node on the stack.", activeLines: [6, 7], activeId: node?.id ?? null, result: null });
    while (node) { stack.push(node); push({ kind: "build", phase: "push", title: `Push ${node.value}`, detail: `${node.value} waits until every value in its left subtree has been visited.`, activeLines: [7, 8], activeId: node.id, result: null }); node = node.left; }
    node = stack.pop()!; push({ kind: "visit", phase: "pop", title: `Pop ${node.value}`, detail: "Its left subtree is done, so this is the smallest unvisited value.", activeLines: [11], activeId: node.id, result: null });
    remaining -= 1; visitedIds.push(node.id); visitedValues.push(node.value); push({ kind: "found", phase: "count", title: `Count ${node.value} as inorder #${visitedValues.length}`, detail: `k decreases to ${remaining}.`, activeLines: [12], activeId: node.id, result: null });
    if (remaining === 0) { result = node.value; push({ kind: "found", phase: "found", title: `${node.value} is the answer`, detail: "This is exactly the kth node popped in sorted inorder order.", activeLines: [13, 14], activeId: node.id, result }); break; }
    node = node.right; push({ kind: "visit", phase: "right", title: `Move right from ${visitedValues[visitedValues.length - 1]}`, detail: node ? `Next, traverse the right subtree rooted at ${node.value}.` : "There is no right subtree; pop the next waiting ancestor.", activeLines: [15], activeId: node?.id ?? null, result: null });
  }
  push({ kind: "done", phase: "done", title: `Return ${result}`, detail: "The explicit stack gives the same order as recursive inorder traversal.", activeLines: [14], activeId: null, result }); return { frames };
}
function suffix(n: number) { return n % 10 === 1 && n % 100 !== 11 ? "st" : n % 10 === 2 && n % 100 !== 12 ? "nd" : n % 10 === 3 && n % 100 !== 13 ? "rd" : "th"; }
function build(values: Array<number | null>): Node | null { if (typeof values[0] !== "number") return null; const root: Node = { id: "node-0", value: values[0], left: null, right: null }; const queue = [root]; let i = 1; while (queue.length && i < values.length) { const parent = queue.shift()!; const left = values[i]; const li = i++; if (typeof left === "number") { parent.left = { id: `node-${li}`, value: left, left: null, right: null }; queue.push(parent.left); } if (i >= values.length) break; const right = values[i]; const ri = i++; if (typeof right === "number") { parent.right = { id: `node-${ri}`, value: right, left: null, right: null }; queue.push(parent.right); } } return root; }
