import { useEffect, useMemo, useState } from "react";
import ReactFlow, { Background, Controls, MarkerType, Position } from "reactflow";
import type { Edge, Node } from "reactflow";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import { flattenTree } from "../0094-binary-tree-inorder-traversal/dryRun";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type KthSmallestBstInput } from "./data";
import { createKthSmallestBstDryRun } from "./dryRun";
export default function KthSmallestBstVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id), [input, setInput] = useState<KthSmallestBstInput>(defaultExample.input), [text, setText] = useState(JSON.stringify(defaultExample.input)), [step, setStep] = useState(0), [playing, setPlaying] = useState(false), [error, setError] = useState(""); const run = useMemo(() => createKthSmallestBstDryRun(input.root, input.k), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const tree = useMemo(() => flattenTree(input.root), [input.root]); const selected = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((current) => current + 1), 650); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  const nodes = useMemo<Node[]>(() => tree.map((node) => ({ id: node.id, position: position(node.layoutIndex), sourcePosition: Position.Bottom, targetPosition: Position.Top, className: ["combo-node", "bst-node", frame.activeId === node.id ? "is-active" : frame.visitedIds.includes(node.id) ? "is-complete" : ""].filter(Boolean).join(" "), data: { label: <div className="combo-node-content"><strong>{node.value}</strong><span>{frame.activeId === node.id ? "current" : frame.visitedIds.includes(node.id) ? `#${frame.visitedIds.indexOf(node.id) + 1}` : "waiting"}</span></div> } })), [frame.activeId, frame.visitedIds, tree]); const edges = useMemo<Edge[]>(() => tree.filter((node) => node.parentId).map((node) => ({ id: `${node.parentId}-${node.id}`, source: node.parentId!, target: node.id, type: "straight", label: node.side, labelBgBorderRadius: 6, labelBgPadding: [6, 3] as [number, number], markerEnd: { type: MarkerType.ArrowClosed }, animated: node.id === frame.activeId })), [frame.activeId, tree]);
  function load(example: typeof defaultExample) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); } function loadInput() { try { const parsed: unknown = JSON.parse(text); if (!valid(parsed)) throw new Error(); setExampleId(0); setInput(parsed); setStep(0); setPlaying(false); setError(""); } catch { setError('Use {"root":[3,1,4,null,2],"k":1}.'); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="kth smallest BST input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load input</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current result"}</span><code>{frame.result ?? "pending"}</code></div></aside><section className="flow-panel combo-flow-panel"><div className="panel-heading"><h2>Inorder traversal of BST</h2><span>green: popped in order</span></div><ReactFlow nodes={nodes} edges={edges} defaultViewport={{ x: 440, y: 52, zoom: 0.88 }} minZoom={0.18} maxZoom={1.6} nodeOrigin={[0.5, 0]}><Background gap={22} size={1} /><Controls /></ReactFlow></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>inorder stack</h3><div className="token-list">{frame.stack.length ? frame.stack.map((id) => <span key={id}>{tree.find((node) => node.id === id)?.value}</span>) : <em>empty</em>}</div></div><div className="state-block"><h3>k and visited values</h3><div className="token-list"><span>k remaining = {frame.kRemaining}</span>{frame.visitedValues.length ? frame.visitedValues.map((value, index) => <span key={`${value}-${index}`}>#{index + 1}: {value}</span>) : <em>none</em>}</div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
function position(index: number) { const depth = Math.floor(Math.log2(index + 1)), first = 2 ** depth - 1, spacing = 180 / (2 ** Math.max(depth - 1, 0)); return { x: (index - first - (2 ** depth - 1) / 2) * spacing, y: depth * 132 }; }
function valid(value: unknown): value is KthSmallestBstInput { return typeof value === "object" && value !== null && "root" in value && "k" in value && Array.isArray(value.root) && value.root.length > 0 && value.root.length <= 31 && value.root.every((node) => node === null || (typeof node === "number" && Number.isFinite(node))) && typeof value.k === "number" && Number.isInteger(value.k) && value.k > 0 && value.k <= value.root.filter((node) => typeof node === "number").length; }
