import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type TopKFrequentExample, type TopKFrequentInput } from "./data";
import { createTopKFrequentDryRun } from "./dryRun";

export default function TopKFrequentVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id), [input, setInput] = useState<TopKFrequentInput>(defaultExample.input), [text, setText] = useState(JSON.stringify(defaultExample.input)), [step, setStep] = useState(0), [playing, setPlaying] = useState(false), [error, setError] = useState("");
  const run = useMemo(() => createTopKFrequentDryRun(input.nums, input.k), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selected = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((current) => current + 1), 650); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  function load(example: TopKFrequentExample) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const parsed: unknown = JSON.parse(text); if (!valid(parsed)) throw new Error(); setExampleId(0); setInput(parsed); setStep(0); setPlaying(false); setError(""); } catch { setError('Use {"nums":[1,1,1,2,2,3],"k":2}.'); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="top k frequent input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load input</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current result"}</span><code>{frame.result ? JSON.stringify(frame.result) : "pending"}</code></div></aside><section className="flow-panel product-flow-panel"><div className="panel-heading"><h2>Frequency table and size-k heap</h2><span>yellow: scanned number, green: retained heap entries</span></div><div className="product-stage"><div className="product-numbers">{input.nums.map((value, index) => <div className={["product-number", index === frame.index ? "is-current" : ""].filter(Boolean).join(" ")} key={index}><span>index {index}</span><strong>{value}</strong><em>count {frame.counts[String(value)] ?? 0}</em></div>)}</div><div className="product-state-grid"><div className="product-state is-emphasized"><span>count</span><strong>{Object.keys(frame.counts).length ? Object.entries(frame.counts).map(([value, frequency]) => `${value}:${frequency}`).join("  ") : "{}"}</strong></div><div className="product-state is-result"><span>min-heap (frequency, value)</span><strong>{frame.heap.length ? frame.heap.map((entry) => `(${entry.frequency}, ${entry.value})`).join("  ") : "[]"}</strong></div></div><div className="product-phase"><span>k = {input.k}</span><strong>{frame.removed ? `removed ${frame.removed.value}` : frame.title}</strong><p>{frame.detail}</p></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>heap decision</h3><div className="token-list"><span>current = {frame.current ?? "-"}</span><span>removed = {frame.removed ? frame.removed.value : "-"}</span><span>heap size = {frame.heap.length}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}

function valid(value: unknown): value is TopKFrequentInput { if (typeof value !== "object" || value === null) return false; const candidate = value as { nums?: unknown; k?: unknown }; return Array.isArray(candidate.nums) && candidate.nums.length > 0 && candidate.nums.length <= 16 && candidate.nums.every((item) => typeof item === "number" && Number.isInteger(item)) && typeof candidate.k === "number" && Number.isInteger(candidate.k) && candidate.k >= 1 && candidate.k <= new Set(candidate.nums).size; }
