import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type MinimumSizeSubarraySumInput } from "./data";
import { createMinimumSizeSubarraySumDryRun } from "./dryRun";

export default function MinimumSizeSubarraySumVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<MinimumSizeSubarraySumInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createMinimumSizeSubarraySumDryRun(input.target, input.nums), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selected = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((value) => value + 1), 620); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  const load = (example: typeof defaultExample) => { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); };
  const loadInput = () => { try { const parsed: unknown = JSON.parse(text); if (!valid(parsed)) throw new Error(); setExampleId(0); setInput(parsed); setStep(0); setPlaying(false); setError(""); } catch { setError('Use {"target":7,"nums":[2,3,1,2,4,3]}; nums must contain positive integers.'); } };
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((item) => <button className={item.id === exampleId ? "active" : ""} key={item.id} onClick={() => load(item)} type="button">{item.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="minimum size subarray input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load input</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current result"}</span><code>{frame.result ?? "pending"}</code></div></aside><section className="flow-panel product-flow-panel"><div className="panel-heading"><h2>Positive-number sliding window</h2><span>target = {input.target}</span></div><div className="product-stage"><div className="product-numbers">{input.nums.map((num, index) => <div className={["product-number", index === frame.right ? "is-current" : "", index >= frame.left && index <= frame.right ? "is-window" : ""].filter(Boolean).join(" ")} key={index}><span>index {index}</span><strong>{num}</strong></div>)}</div><div className="product-phase"><span>window [left, right]</span><strong>{frame.right >= frame.left ? `[${frame.left}, ${frame.right}]` : "empty"}</strong><p>{frame.detail}</p></div><div className="product-state-grid"><div className="product-state is-emphasized"><span>current sum</span><strong>{frame.sum}</strong></div><div className="product-state is-result"><span>best length</span><strong>{frame.best ?? "-"}</strong></div></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>window state</h3><div className="token-list"><span>left = {frame.left}</span><span>right = {frame.right}</span><span>sum = {frame.sum}</span><span>ans = {frame.best ?? "inf"}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
function valid(value: unknown): value is MinimumSizeSubarraySumInput { return typeof value === "object" && value !== null && "target" in value && "nums" in value && typeof value.target === "number" && Number.isInteger(value.target) && value.target > 0 && Array.isArray(value.nums) && value.nums.length > 0 && value.nums.length <= 20 && value.nums.every((item) => typeof item === "number" && Number.isInteger(item) && item > 0); }
