import { useEffect, useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "./CodeTrace";
import { StepControls } from "./StepControls";
import type { FrameKind, VisualizerProps } from "../types";

export type ArrayTraceFrame = { kind: FrameKind; phase: string; title: string; detail: string; activeLines: number[]; cells: Array<string | number>; activeIndices: number[]; completeIndices: number[]; result: unknown };
type Example<T> = { id: number; label: string; input: T; output: unknown };
type Props<T, F extends ArrayTraceFrame> = VisualizerProps & { title: string; examples: Example<T>[]; codeLines: string[]; heading: string; parseInput: (value: unknown) => T | null; inputLabel: string; errorMessage: string; createRun: (input: T) => { frames: F[] }; renderState: (frame: F) => ReactNode };

export function ArrayTraceVisualizer<T, F extends ArrayTraceFrame>({ onBack, title, examples, codeLines, heading, parseInput, inputLabel, errorMessage, createRun, renderState }: Props<T, F>) {
  const [exampleId, setExampleId] = useState(examples[0]!.id), [input, setInput] = useState(examples[0]!.input), [text, setText] = useState(JSON.stringify(examples[0]!.input)), [step, setStep] = useState(0), [playing, setPlaying] = useState(false), [error, setError] = useState("");
  const run = useMemo(() => createRun(input), [createRun, input]);
  const frame = run.frames[Math.min(step, run.frames.length - 1)]!;
  const selected = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((current) => current + 1), 650); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  function load(example: Example<T>) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const parsed = parseInput(JSON.parse(text)); if (!parsed) throw new Error(); setExampleId(0); setInput(parsed); setStep(0); setPlaying(false); setError(""); } catch { setError(errorMessage); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>{inputLabel}<textarea aria-label={`${title} input JSON`} value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load input</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current result"}</span><code>{JSON.stringify(frame.result)}</code></div></aside><section className="flow-panel product-flow-panel"><div className="panel-heading"><h2>{heading}</h2><span>yellow: current, green: confirmed</span></div><div className="product-stage"><div className="product-numbers">{frame.cells.map((cell, index) => <div className={["product-number", frame.activeIndices.includes(index) ? "is-current" : "", frame.completeIndices.includes(index) ? "is-window" : ""].filter(Boolean).join(" ")} key={index}><span>index {index}</span><strong>{cell}</strong><em>{frame.activeIndices.includes(index) ? "current" : frame.completeIndices.includes(index) ? "confirmed" : ""}</em></div>)}</div><div className="product-phase"><span>{frame.phase}</span><strong>{frame.title}</strong><p>{frame.detail}</p></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div>{renderState(frame)}<CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
