import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type ReverseStringExample, type ReverseStringInput } from "./data";
import { createReverseStringDryRun } from "./dryRun";

export default function ReverseStringVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id), [input, setInput] = useState<ReverseStringInput>(defaultExample.input), [text, setText] = useState(JSON.stringify(defaultExample.input)), [step, setStep] = useState(0), [playing, setPlaying] = useState(false), [error, setError] = useState("");
  const run = useMemo(() => createReverseStringDryRun(input.s), [input]);
  const frame = run.frames[Math.min(step, run.frames.length - 1)]!;
  const selected = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((current) => current + 1), 650); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  function load(example: ReverseStringExample) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const parsed: unknown = JSON.parse(text); if (!valid(parsed)) throw new Error(); setExampleId(0); setInput(parsed); setStep(0); setPlaying(false); setError(""); } catch { setError('Use {"s":["h","e","l","l","o"]}; each item must be one character.'); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="reverse string input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load input</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current result"}</span><code>{frame.result ? JSON.stringify(frame.result) : "pending"}</code></div></aside><section className="flow-panel product-flow-panel"><div className="panel-heading"><h2>In-place mirrored swaps</h2><span>yellow: left, green: right</span></div><div className="product-stage"><div className="product-numbers">{frame.chars.map((char, index) => <div className={["product-number", index === frame.left ? "is-current" : "", index === frame.right ? "is-window" : ""].filter(Boolean).join(" ")} key={index}><span>index {index}</span><strong>{char}</strong><em>{index === frame.left ? "left" : index === frame.right ? "right" : ""}</em></div>)}</div><div className="product-phase"><span>pointers</span><strong>left = {frame.left ?? "-"}, right = {frame.right ?? "-"}</strong><p>{frame.detail}</p></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>pointer variables</h3><div className="token-list"><span>left = {frame.left ?? "-"}</span><span>right = {frame.right ?? "-"}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}

function valid(value: unknown): value is ReverseStringInput { if (typeof value !== "object" || value === null) return false; const candidate = value as { s?: unknown }; return Array.isArray(candidate.s) && candidate.s.length <= 16 && candidate.s.every((item) => typeof item === "string" && [...item].length === 1); }
