import type { FrameKind } from "../../shared/types";
type T = { id: string; value: number; left: T | null; right: T | null };
export type SymmetricTreeFrame = { kind: FrameKind; phase: "start" | "compare" | "mirror-left" | "mirror-right" | "mismatch" | "match" | "done"; title: string; detail: string; activeLines: number[]; leftId: string | null; rightId: string | null; stack: string[]; result: boolean | null };
export function createSymmetricTreeDryRun(values: Array<number | null>): { frames: SymmetricTreeFrame[] } {
  const root = build(values); const frames: SymmetricTreeFrame[] = []; const stack: string[] = []; const push = (frame: Omit<SymmetricTreeFrame, "stack">) => frames.push({ ...frame, stack: [...stack] });
  push({ kind: "start", phase: "start", title: "Start at the two children of root", detail: "A tree is symmetric when its left and right subtrees are mirror images.", activeLines: [12], leftId: root?.left?.id ?? null, rightId: root?.right?.id ?? null, result: null });
  const result = root ? mirror(root.left, root.right) : true;
  push({ kind: "done", phase: "done", title: result ? "The tree is symmetric" : "The mirror check failed", detail: result ? "Every mirrored pair matches in value and structure." : "A mirrored pair has a missing or different node.", activeLines: [12], leftId: null, rightId: null, result }); return { frames };
  function mirror(left: T | null, right: T | null): boolean {
    stack.push(`mirror(${left?.value ?? "None"}, ${right?.value ?? "None"})`); push({ kind: "visit", phase: "compare", title: `Compare ${left?.value ?? "None"} and ${right?.value ?? "None"}`, detail: "Compare nodes that face each other across the tree's center line.", activeLines: [5], leftId: left?.id ?? null, rightId: right?.id ?? null, result: null });
    if (!left && !right) { push({ kind: "found", phase: "match", title: "Both mirrored positions are empty", detail: "This pair is symmetric.", activeLines: [6, 7], leftId: null, rightId: null, result: true }); stack.pop(); return true; }
    if (!left || !right || left.value !== right.value) { push({ kind: "prune", phase: "mismatch", title: "This mirrored pair differs", detail: !left || !right ? "One side has a node while the other side is empty." : `${left.value} does not equal ${right.value}.`, activeLines: [8, 9], leftId: left?.id ?? null, rightId: right?.id ?? null, result: false }); stack.pop(); return false; }
    push({ kind: "start", phase: "mirror-left", title: `Cross-compare ${left.value}.left with ${right.value}.right`, detail: "The outside children must mirror each other.", activeLines: [11], leftId: left.left?.id ?? null, rightId: right.right?.id ?? null, result: null }); const outside = mirror(left.left, right.right); if (!outside) { stack.pop(); return false; }
    push({ kind: "start", phase: "mirror-right", title: `Cross-compare ${left.value}.right with ${right.value}.left`, detail: "The inside children must mirror each other.", activeLines: [11], leftId: left.right?.id ?? null, rightId: right.left?.id ?? null, result: null }); const inside = mirror(left.right, right.left); stack.pop(); return inside;
  }
}
function build(values: Array<number | null>): T | null { if (typeof values[0] !== "number") return null; const root: T = { id: "node-0", value: values[0], left: null, right: null }; const q=[root]; let i=1; while(q.length&&i<values.length){const n=q.shift()!;const l=values[i],li=i++;if(typeof l==="number"){n.left={id:`node-${li}`,value:l,left:null,right:null};q.push(n.left);}if(i>=values.length)break;const r=values[i],ri=i++;if(typeof r==="number"){n.right={id:`node-${ri}`,value:r,left:null,right:null};q.push(n.right);}}return root;}
