import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import ReactFlow, { Background, Controls, MarkerType, Position } from "reactflow";
import type { Edge, Node, ReactFlowInstance } from "reactflow";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type IntersectionInput } from "./data";
import { createIntersectionDryRun, type IntersectionNode } from "./dryRun";

export default function IntersectionVisualizer({ onBack }: VisualizerProps) {
  const panelRef = useRef<HTMLElement | null>(null); const flowRef = useRef<ReactFlowInstance | null>(null);
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<IntersectionInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createIntersectionDryRun(input.aPrefix, input.bPrefix, input.shared), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selected = examples.find((example) => example.id === exampleId);
  const resetViewport = useCallback(() => { const width = panelRef.current?.clientWidth ?? 680; const furthestNode = Math.max(...run.nodes.map((node) => nodePosition(node, input).x), 0) + 130; const zoom = Math.min(0.72, Math.max(0.28, (width - 116) / furthestNode)); flowRef.current?.setViewport({ x: 58, y: 44, zoom }); }, [input, run.nodes]);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((current) => current + 1), 650); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  useEffect(() => { const request = window.requestAnimationFrame(resetViewport); return () => window.cancelAnimationFrame(request); }, [resetViewport]);
  const nodes = useMemo<Node[]>(() => run.nodes.map((node) => { const active = node.id === frame.pointerA || node.id === frame.pointerB; const roles = [[node.id === frame.pointerA, "pointerA"], [node.id === frame.pointerB, "pointerB"], [node.lane === "shared", "shared tail"]].flatMap(([match, label]) => match ? [label as string] : []); return { id: node.id, position: nodePosition(node, input), sourcePosition: Position.Right, targetPosition: Position.Left, className: ["combo-node", active ? "is-active" : frame.completedIds.includes(node.id) ? "is-complete" : ""].filter(Boolean).join(" "), data: { label: <div className="combo-node-content"><strong>{node.value}</strong><span>{roles.join(" | ") || (node.lane === "a" ? "list A" : "list B")}</span></div> } }; }), [frame.completedIds, frame.pointerA, frame.pointerB, input, run.nodes]);
  const edges = useMemo<Edge[]>(() => Object.entries(frame.links).flatMap(([source, target]) => target ? [{ id: `${source}-${target}`, source, target, type: "smoothstep", label: "next", labelBgBorderRadius: 6, labelBgPadding: [6, 3], markerEnd: { type: MarkerType.ArrowClosed }, animated: source === frame.pointerA || source === frame.pointerB, style: { stroke: source === frame.pointerA || source === frame.pointerB ? "#d9973c" : target.startsWith("s-") ? "#268366" : "#52728e", strokeWidth: target.startsWith("s-") ? 2.35 : 1.6 } }] : []), [frame.links, frame.pointerA, frame.pointerB]);
  const load = (example: typeof defaultExample) => { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); };
  const loadInput = () => { try { const parsed: unknown = JSON.parse(text); if (!valid(parsed)) throw new Error(); setExampleId(0); setInput(parsed); setStep(0); setPlaying(false); setError(""); } catch { setError('Use {"aPrefix":[4,1],"bPrefix":[5,6,1],"shared":[8,4,5]}.'); } };
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>prefix and shared-tail JSON<textarea aria-label="intersection input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load lists</button></div><div className="expected-output"><span>{selected ? `${selected.label} intersection value` : "Current intersection value"}</span><code>{frame.result ?? "pending"}</code></div></aside><section className="flow-panel combo-flow-panel" ref={panelRef}><div className="panel-heading"><h2>Two list heads, one shared tail</h2><span>yellow: pointers, green: shared suffix</span></div><ReactFlow nodes={nodes} edges={edges} defaultViewport={{ x: 58, y: 44, zoom: 0.6 }} minZoom={0.18} maxZoom={1.6} nodeOrigin={[0.5, 0]} onInit={(instance) => { flowRef.current = instance; window.requestAnimationFrame(resetViewport); }}><Background gap={22} size={1} /><Controls /></ReactFlow></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>two pointers</h3><div className="token-list"><span>pointerA = {label(frame.pointerA, run.nodes)}</span><span>pointerB = {label(frame.pointerB, run.nodes)}</span><span>shared tail = [{input.shared.join(", ") || "none"}]</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}

function nodePosition(node: IntersectionNode, input: IntersectionInput): { x: number; y: number } { const prefixWidth = Math.max(input.aPrefix.length, input.bPrefix.length) * 142; if (node.lane === "a") return { x: node.offset * 142, y: 108 }; if (node.lane === "b") return { x: node.offset * 142, y: 290 }; return { x: prefixWidth + 110 + node.offset * 142, y: 199 }; }
function valid(value: unknown): value is IntersectionInput { return typeof value === "object" && value !== null && "aPrefix" in value && "bPrefix" in value && "shared" in value && [value.aPrefix, value.bPrefix, value.shared].every((list) => Array.isArray(list) && list.length <= 8 && list.every((item) => typeof item === "number" && Number.isFinite(item))) && ((value.aPrefix as unknown[]).length > 0 || (value.shared as unknown[]).length > 0) && ((value.bPrefix as unknown[]).length > 0 || (value.shared as unknown[]).length > 0); }
function label(nodeId: string | null, nodes: IntersectionNode[]): string { return nodeId === null ? "None" : String(nodes.find((node) => node.id === nodeId)?.value); }
