export type EvaluateDivisionInput = { equations: string[][]; values: number[]; queries: string[][] };

export const title = "399. Evaluate Division";
export const examples = [
  { id: 1, label: "LeetCode 1", input: { equations: [["a", "b"], ["b", "c"]], values: [2, 3], queries: [["a", "c"], ["b", "a"], ["a", "e"], ["a", "a"], ["x", "x"]] }, output: [6, 0.5, -1, 1, -1] },
  { id: 2, label: "LeetCode 2", input: { equations: [["a", "b"], ["b", "c"], ["bc", "cd"]], values: [1.5, 2.5, 5], queries: [["a", "c"], ["c", "b"], ["bc", "cd"], ["cd", "bc"]] }, output: [3.75, 0.4, 5, 0.2] },
] satisfies Array<{ id: number; label: string; input: EvaluateDivisionInput; output: number[] }>;
export const defaultExample = examples[0]!;
export const codeLines = [
  "class Solution:",
  "    def calcEquation(",
  "        self,",
  "        equations: List[List[str]],",
  "        values: List[float],",
  "        queries: List[List[str]]",
  "    ) -> List[float]:",
  "",
  "        graph = defaultdict(list)",
  "",
  "        for (a, b), value in zip(equations, values):",
  "            graph[a].append((b, value))",
  "            graph[b].append((a, 1 / value))",
  "",
  "        def dfs(cur, target, visited):",
  "            if cur == target:",
  "                return 1.0",
  "",
  "            visited.add(cur)",
  "",
  "            for nei, weight in graph[cur]:",
  "                if nei in visited:",
  "                    continue",
  "",
  "                res = dfs(nei, target, visited)",
  "",
  "                if res != -1.0:",
  "                    return weight * res",
  "",
  "            return -1.0",
  "",
  "        ans = []",
  "",
  "        for a, b in queries:",
  "            # 如果变量根本没出现过",
  "            if a not in graph or b not in graph:",
  "                ans.append(-1.0)",
  "            else:",
  "                ans.append(dfs(a, b, set()))",
  "",
  "        return ans",
];
