import type { TrieOperation } from "../../shared/types";

export const title = "Add and Search Word: Trie + Wildcard DFS";

export const codeLines = [
  "class TrieNode:",
  "    def __init__(self):",
  "        self.children = {}",
  "",
  "        self.is_end = False",
  "",
  "",
  "class WordDictionary:",
  "",
  "    def __init__(self):",
  "        self.root = TrieNode()",
  "",
  "    def addWord(self, word: str) -> None:",
  "        node = self.root",
  "",
  "        for char in word:",
  "            if char not in node.children:",
  "                node.children[char] = TrieNode()",
  "",
  "            node = node.children[char]",
  "",
  "        node.is_end = True",
  "",
  "    def search(self, word: str) -> bool:",
  "",
  "        def dfs(index, node):",
  "            if index == len(word):",
  "                return node.is_end",
  "",
  "            char = word[index]",
  "",
  "            # 普通字符：只需要匹配对应的子节点",
  "            if char != \".\":",
  "                if char not in node.children:",
  "                    return False",
  "",
  "                return dfs(index + 1, node.children[char])",
  "",
  "            # 遇到 \".\"：尝试当前节点的所有子节点",
  "            for child in node.children.values():",
  "                if dfs(index + 1, child):",
  "                    return True",
  "",
  "            return False",
  "",
  "        return dfs(0, self.root)",
];

export const operations: TrieOperation[] = [
  { name: "WordDictionary", args: [], output: "null" },
  { name: "addWord", args: ["bad"], output: "null" },
  { name: "addWord", args: ["dad"], output: "null" },
  { name: "addWord", args: ["mad"], output: "null" },
  { name: "search", args: ["pad"], output: "false" },
  { name: "search", args: ["bad"], output: "true" },
  { name: "search", args: [".ad"], output: "true" },
  { name: "search", args: ["b.."], output: "true" },
];
