import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type RotateArrayInput } from "./data";
import { createRotateArrayDryRun } from "./dryRun";

export default function RotateArrayVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<RotateArrayInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createRotateArrayDryRun(input.nums, input.k), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selected = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((current) => current + 1), 650); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  const load = (example: typeof defaultExample) => { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); };
  const loadInput = () => { try { const parsed: unknown = JSON.parse(text); if (!valid(parsed)) throw new Error(); setExampleId(0); setInput(parsed); setStep(0); setPlaying(false); setError(""); } catch { setError('Use {"nums":[1,2,3,4,5,6,7],"k":3}.'); } };
  const inRange = (index: number) => frame.range !== null && index >= frame.range[0] && index <= frame.range[1];
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="rotate array input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load input</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current result"}</span><code>{JSON.stringify(frame.result ?? "pending")}</code></div></aside><section className="flow-panel product-flow-panel"><div className="panel-heading"><h2>Three in-place reversals</h2><span>k = {frame.k}</span></div><div className="product-stage"><div className="product-numbers">{frame.nums.map((value, index) => <div className={["product-number", inRange(index) ? "is-window" : "", frame.active?.includes(index) ? "is-current" : ""].filter(Boolean).join(" ")} key={`${index}-${value}`}><span>index {index}</span><strong>{value}</strong></div>)}</div><div className="product-phase"><span>active range</span><strong>{frame.range ? `[${frame.range[0]}, ${frame.range[1]}]` : "none"}</strong><p>{frame.detail}</p></div><div className="product-state-grid"><div className="product-state is-emphasized"><span>swap pair</span><strong>{frame.active ? `[${frame.active.join(", ")}]` : "-"}</strong></div><div className="product-state is-result"><span>phase</span><strong>{frame.phase}</strong></div></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>variables</h3><div className="token-list"><span>k = {frame.k}</span><span>nums = [{frame.nums.join(", ")}]</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}

function valid(value: unknown): value is RotateArrayInput { return typeof value === "object" && value !== null && "nums" in value && "k" in value && Array.isArray(value.nums) && value.nums.length > 0 && value.nums.length <= 20 && value.nums.every((item) => typeof item === "number" && Number.isFinite(item)) && typeof value.k === "number" && Number.isInteger(value.k) && value.k >= 0; }
