import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type TwoSumSortedInput } from "./data";
import { createTwoSumSortedDryRun } from "./dryRun";

export default function TwoSumSortedVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<TwoSumSortedInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createTwoSumSortedDryRun(input.numbers, input.target), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selected = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((current) => current + 1), 650); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  const load = (example: typeof defaultExample) => { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); };
  const loadInput = () => { try { const parsed: unknown = JSON.parse(text); if (!valid(parsed)) throw new Error(); setExampleId(0); setInput(parsed); setStep(0); setPlaying(false); setError(""); } catch { setError('Use {"numbers":[2,7,11,15],"target":9}; numbers must be sorted.'); } };
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="two sum sorted input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load input</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current output"}</span><code>{frame.result ? JSON.stringify(frame.result) : "pending"}</code></div></aside><section className="flow-panel binary-flow-panel"><div className="panel-heading"><h2>Sorted two-pointer search</h2><span>target = {input.target}</span></div><div className="binary-stage"><div className="binary-array">{input.numbers.map((value, index) => <div className={["binary-cell", index === frame.left ? "is-left" : "", index === frame.right ? "is-right" : "", frame.result?.includes(index + 1) ? "is-found" : "", index < frame.left || index > frame.right ? "is-discarded" : ""].filter(Boolean).join(" ")} key={index}><strong>{value}</strong><span>{index === frame.left ? "left" : index === frame.right ? "right" : `i = ${index}`}</span></div>)}</div><div className="product-state-grid"><div className="product-state is-emphasized"><span>current sum</span><strong>{frame.sum ?? "pending"}</strong></div><div className="product-state is-result"><span>answer positions</span><strong>{frame.result ? JSON.stringify(frame.result) : "searching"}</strong></div></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>pointers</h3><div className="token-list"><span>left = {frame.left}</span><span>right = {frame.right}</span><span>sum = {frame.sum ?? "pending"}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
function valid(value: unknown): value is TwoSumSortedInput { return typeof value === "object" && value !== null && "numbers" in value && "target" in value && Array.isArray(value.numbers) && value.numbers.length >= 2 && value.numbers.length <= 16 && value.numbers.every((item) => typeof item === "number" && Number.isFinite(item)) && value.numbers.every((item, index, values) => index === 0 || values[index - 1]! <= item) && typeof value.target === "number" && Number.isFinite(value.target); }
