import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { Cell, VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type ValidSudokuInput } from "./data";
import { createValidSudokuDryRun } from "./dryRun";

export default function ValidSudokuVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<ValidSudokuInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const run = useMemo(() => createValidSudokuDryRun(input.board), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!; const selectedExample = examples.find((example) => example.id === exampleId);
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((value) => value + 1), 480); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  function load(example: (typeof examples)[number]) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const candidate = JSON.parse(text) as ValidSudokuInput; if (!candidate || !Array.isArray(candidate.board) || candidate.board.length !== 9 || !candidate.board.every((row) => Array.isArray(row) && row.length === 9 && row.every((value) => value === "." || /^[1-9]$/.test(value)))) throw new Error(); setInput(candidate); setExampleId(0); setStep(0); setPlaying(false); setError(""); } catch { setError('Use a 9x9 JSON board with "." and digits 1 through 9.'); } }
  const sameCell = (left: Cell | null, right: Cell) => left !== null && left[0] === right[0] && left[1] === right[1];
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="input-grid"><label>input JSON<textarea aria-label="input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load board</button></div><div className="expected-output"><span>{selectedExample ? selectedExample.label + " output" : "Current result"}</span><code>{String(frame.result ?? selectedExample?.output ?? "pending")}</code></div></aside><section className="flow-panel sudoku-flow-panel"><div className="panel-heading"><h2>Row / Column / Box Validation</h2><span>{frame.box === null ? "ready" : "box " + frame.box}</span></div><div className="sudoku-stage"><div className="sudoku-board">{frame.board.flatMap((row, rowIndex) => row.map((value, colIndex) => <div className={["sudoku-cell", sameCell(frame.current, [rowIndex, colIndex]) ? "is-current" : "", sameCell(frame.conflictCell, [rowIndex, colIndex]) ? "is-conflict" : "", Math.floor(rowIndex / 3) * 3 + Math.floor(colIndex / 3) === frame.box && frame.current ? "is-box" : ""].filter(Boolean).join(" ")} key={rowIndex + "-" + colIndex}><strong>{value === "." ? "" : value}</strong><span>{rowIndex},{colIndex}</span></div>))}</div><div className="sudoku-set-grid"><SetCard label={"row " + (frame.current?.[0] ?? "-")} values={frame.rowValues} /><SetCard label={"column " + (frame.current?.[1] ?? "-")} values={frame.colValues} /><SetCard label={"box " + (frame.box ?? "-")} values={frame.boxValues} /></div><div className="product-phase"><span>validation step</span><strong>{frame.conflict ? "conflict: " + frame.conflict : frame.current ? "checking " + frame.current.join(", ") : "complete"}</strong><p>{frame.detail}</p></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={"event-card " + frame.kind}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
function SetCard({ label, values }: { label: string; values: string[] }) { return <div className="sudoku-set-card"><span>{label}</span><strong>{values.length ? "{ " + values.join(", ") + " }" : "{}"}</strong></div>; }
