import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Upload } from "lucide-react";
import { CodeTrace } from "../../shared/components/CodeTrace";
import { StepControls } from "../../shared/components/StepControls";
import type { VisualizerProps } from "../../shared/types";
import { codeLines, defaultExample, examples, title, type StackInput, type StackOperation } from "./data";
import { createStackUsingQueuesDryRun } from "./dryRun";

export default function StackUsingQueuesVisualizer({ onBack }: VisualizerProps) {
  const [exampleId, setExampleId] = useState(defaultExample.id); const [input, setInput] = useState<StackInput>(defaultExample.input); const [text, setText] = useState(JSON.stringify(defaultExample.input)); const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [error, setError] = useState("");
  const selected = examples.find((example) => example.id === exampleId); const run = useMemo(() => createStackUsingQueuesDryRun(input.operations), [input]); const frame = run.frames[Math.min(step, run.frames.length - 1)]!;
  useEffect(() => { if (!playing || step >= run.frames.length - 1) { if (step >= run.frames.length - 1) setPlaying(false); return; } const timer = window.setTimeout(() => setStep((value) => value + 1), 620); return () => window.clearTimeout(timer); }, [playing, run.frames.length, step]);
  function load(example: (typeof examples)[number]) { setExampleId(example.id); setInput(example.input); setText(JSON.stringify(example.input)); setStep(0); setPlaying(false); setError(""); }
  function loadInput() { try { const candidate = JSON.parse(text) as StackInput; if (!candidate || !Array.isArray(candidate.operations) || !candidate.operations.every(isOperation)) throw new Error(); setInput(candidate); setExampleId(0); setStep(0); setPlaying(false); setError(""); } catch { setError("Use JSON such as {\"operations\":[{\"method\":\"push\",\"value\":1},{\"method\":\"pop\"}]}"); } }
  return <main className="app-shell"><header className="topbar"><div><button className="back-link compact" onClick={onBack} type="button"><ArrowLeft size={16} />Catalog</button><p className="eyebrow">AlgoTrace dry run</p><h1>{title}</h1></div><div className="step-pill">Step {step + 1} / {run.frames.length}</div></header><section className="workspace"><aside className="board-panel"><div className="example-switcher" aria-label="LeetCode examples"><span>LeetCode examples</span><div>{examples.map((example) => <button className={example.id === exampleId ? "active" : ""} key={example.id} onClick={() => load(example)} type="button">{example.id}</button>)}</div></div><div className="panel-heading"><h2>operations</h2><span>{input.operations.length} calls</span></div><div className="input-grid"><label>input JSON<textarea aria-label="input JSON" value={text} onChange={(event) => setText(event.target.value)} /></label>{error ? <p className="error">{error}</p> : null}<button className="command load" onClick={loadInput} type="button"><Upload size={16} />Load operations</button></div><div className="expected-output"><span>{selected ? `${selected.label} output` : "Current output"}</span><code>{JSON.stringify(selected?.output ?? frame.output)}</code></div></aside><section className="flow-panel product-flow-panel"><div className="panel-heading"><h2>LIFO Stack Through One Queue</h2><span>queue front is stack top</span></div><div className="product-stage"><div className="product-numbers">{input.operations.map((operation, index) => <div className={`product-number ${index === frame.operationIndex ? "is-current" : ""}`} key={`${operation.method}-${index}`}><span>#{index + 1}</span><strong>{formatOperation(operation)}</strong></div>)}</div><div className="product-phase"><span>current operation</span><strong>{frame.operationIndex === null ? "complete" : formatOperation(frame.operation!)}</strong><p>{frame.detail}</p></div><div className="product-state-grid"><div className="product-state is-emphasized"><span>queue</span><strong>{frame.queue.length ? `[${frame.queue.join(", ")}]` : "[]"}</strong><small>front / stack top</small></div></div></div></section><aside className="state-panel"><div className="state-sticky"><div className={`event-card ${frame.kind}`}><p className="eyebrow">{frame.phase}</p><h2>{frame.title}</h2><p>{frame.detail}</p></div><StepControls frameCount={run.frames.length} playing={playing} step={step} onPlayingChange={setPlaying} onStepChange={setStep} /></div><div className="state-block"><h3>return value</h3><div className="token-list"><span>{frame.output === null ? "no return" : String(frame.output)}</span></div></div><CodeTrace activeLines={frame.activeLines} codeLines={codeLines} /></aside></section></main>;
}
function formatOperation(operation: StackOperation) { return operation.method === "push" ? `push(${operation.value})` : `${operation.method}()`; }
function isOperation(value: unknown): value is StackOperation { if (!value || typeof value !== "object") return false; const candidate = value as { method?: unknown; value?: unknown }; return (candidate.method === "push" && Number.isFinite(candidate.value)) || candidate.method === "pop" || candidate.method === "top" || candidate.method === "empty"; }
